apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  GMAIL_API_ENABLED: "true"
  FROM_EMAIL: "joaquin.gonzalez.c@estudiantes.utec.edu.uy"
  SERVICE_NAME: "User Notifications"
  GMAIL_CREDENTIALS_FILE: "/app/secrets/credentials.json"
  GMAIL_TOKEN_FILE: "/app/secrets/token.json"
  NOTIFY_API_TOKEN: "dev-secret"

